var main_trials = [
	{focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 0,
     otherShape: "circle",
     size: 50,
     total: 1,
     rows: 1,
		 location: "top"
    },
    {focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 0,
     otherShape: "circle",
     size: 50,
     total: 1,
     rows: 1,
		 location: "right"
    },
		{focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 0,
     otherShape: "circle",
     size: 50,
     total: 1,
     rows: 1,
		 location: "left"
    },
		{focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 0,
     otherShape: "circle",
     size: 50,
     total: 1,
     rows: 1,
		 location: "left"
    },
    {focalColor: "blue",
     otherColor: "red",
     focalShape: "square",
     focalNumber: 0,
     otherShape: "square",
     size: 50,
     total: 1,
     rows: 1,
		 location: "bot"
    },
    {focalColor: "green",
     otherColor: "yellow",
     focalShape: "triangle",
     focalNumber: 0,
     otherShape: "square",
     size: 100,
     total: 1,
     rows: 1,
		 location: "center"
    },
    {focalColor: "blue",
     otherColor: "red",
     focalShape: "square",
     focalNumber: 0,
     otherShape: "square",
     size: 50,
     total: 1,
     rows: 1,
		 location: "bottom"
    }
];
